<a href="https://colab.research.google.com/github/Andres-Nicolas/CIP/blob/main/clase3_cip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array_basico  = np.array([1,2,3,4,5])

array_basico*5
print(array_basico.sum())
print(array_basico.max())
print(array_basico.min())

print(array_basico[2:])
print(array_basico[:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


'\narray_basico*5\nprint(array_basico.sum())\nprint(array_basico.max())\nprint(array_basico.min())\n\nprint(array_basico[2:])\nprint(array_basico[:2])\n'

In [ ]:
multidimensional=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
multidimensional[:2,1:]
#print(multidimensional.sum())
#print(multidimensional.max())
#print(multidimensional.min())

78
12
1


In [ ]:
import pandas as pd
fuchibol_dicc={
    "jugador":["lionel messi","cr7"],
    "año":["2017","2019"],
    "goles":["37","25"]
}
data=pd.DataFrame(fuchibol_dicc)
print(data)

        jugador   año goles
0  lionel messi  2017    37
1           cr7  2019    25


In [3]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import plotly.express as px

path_file="/content/drive/MyDrive/Colab Notebooks/test.csv"
df=pd.read_csv(path_file,sep=",",header=0)
print(df.head())

df.columns
df.columns=['id;name;age;gender']
df.info()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  codigo;nombre;edad;genero
0        1;Adrian;20;Hombre
1        2;Julian;23;Hombre
2        3;Shirley;19;Mujer
3     4;Sebastian;18;Hombre
4    5;Geison;35;Indefinido
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   id;name;age;gender  5 non-null      object
dtypes: object(1)
memory usage: 168.0+ bytes


In [14]:
import pandas as pd
data= {
    'id': range(1, 21),
    'name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack',
        'Kathy', 'Leo', 'Mona', 'Nate', 'Olivia', 'Paul', 'Quinn', 'Rose', 'Steve', 'Tina'
    ],
    'age': [25, 30, 35, 40, 28, 32, 27, 45, 29, 34, 26, 31, 36, 33, 24, 39, 42, 38, 37, 41],
    'gender': [
        'F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M',
        'F', 'M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'F'
    ]
}

df = pd.DataFrame(data)

file_path = '/content/drive/MyDrive/Colab Notebooks/prueba.csv'
df.to_csv(file_path, index=False, sep=';')

file_path


'/content/drive/MyDrive/Colab Notebooks/prueba.csv'

In [7]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

path_file = "/content/drive/MyDrive/Colab Notebooks/prueba.csv"

df = pd.read_csv(path_file, sep=",", header=0)
print("Columnas disponibles en el archivo:")
print(df.columns)

unicos = df['gender'].unique()
print("\nValores únicos en la columna 'gender':")
print(unicos)

conteo_unicos = df['gender'].value_counts()
print("\nValores totales en la columna 'gender':")
print(conteo_unicos)

total_unicos=df['gender'].nunique()
print("\nTotal de valores únicos en la columna 'gender':")
print(total_unicos)

filas_unicas=df['gender'].drop_duplicates()
print("\nFilas únicas en la columna 'gender':")
print(filas_unicas)

estadistico=df['gender'].describe()
print("\nEstadísticas descriptivas de la columna 'gender':")
print(estadistico)

moda=df['gender'].mode()
print("\nModa de la columna 'gender':")
print(moda)

filas=df[df['gender'].isin(['F'])]
print("\nFilas con el valor 'F' en la columna 'gender':")
print(filas)

duplicados=df.duplicated(subset=['gender'])
print("\nFilas duplicadas en la columna 'gender':")
print(duplicados)



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Columnas disponibles en el archivo:
Index(['id', 'name', 'age', 'gender'], dtype='object')

Valores únicos en la columna 'gender':
['F' 'M']

Valores totales en la columna 'gender':
gender
M    11
F     9
Name: count, dtype: int64

Total de valores únicos en la columna 'gender':
2

Filas únicas en la columna 'gender':
0    F
1    M
Name: gender, dtype: object

Estadísticas descriptivas de la columna 'gender':
count     20
unique     2
top        M
freq      11
Name: gender, dtype: object

Moda de la columna 'gender':
0    M
Name: gender, dtype: object

Filas con el valor 'F' en la columna 'gender':
    id    name  age gender
0    1   Alice   25      F
4    5     Eve   28      F
6    7   Grace   27      F
8    9     Ivy   29      F
10  11   Kathy   26      F
12  13    Mona   36      F
14  15  Olivia   24      F
17  18    Rose   38      F
19  20    Tina   41   